apiVersion: v2
name: memgraph-platform
home: https://memgraph.com/
type: application
description: Memgraph Platform is a single docker image containing Memgraph, query modules from Memgraph Mage and Memgraph Lab.

version: 0.1.1
appVersion: "2.13.0-memgraph2.13.0-lab2.10.0"

keywords:
- graph
- database
- cypher
- analytics
icon: https://public-assets.memgraph.com/memgraph-logo/logo-large.png
sources:
- https://github.com/memgraph/memgraph-platform
maintainers:
- name: Memgraph
  email: tech@memgraph.com
- name: tewnut
  email: tewnut@gmail.com
